#line 2 "ptsLex.yy.cpp"
/* A lexical scanner generated by flex */

/* Scanner skeleton version:
 * $Header: /home/daffy/u0/vern/flex/RCS/flex.skl,v 2.91 96/09/10 16:58:48 vern Exp $
 */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5



/* cfront 1.2 defines "c_plusplus" instead of "__cplusplus" */
#ifdef c_plusplus
#ifndef __cplusplus
#define __cplusplus
#endif
#endif


#ifdef __cplusplus

#include <stdlib.h>
class istream;
#include <unistd.h>

/* Use prototypes in function declarations. */
#define YY_USE_PROTOS

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

#if __STDC__

#define YY_USE_PROTOS
#define YY_USE_CONST

#endif	/* __STDC__ */
#endif	/* ! __cplusplus */

#ifdef __TURBOC__
 #pragma warn -rch
 #pragma warn -use
#include <io.h>
#include <stdlib.h>
#define YY_USE_CONST
#define YY_USE_PROTOS
#endif

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif


#ifdef YY_USE_PROTOS
#define YY_PROTO(proto) proto
#else
#define YY_PROTO(proto) ()
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yy_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yy_start - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#define YY_BUF_SIZE 16384

typedef struct yy_buffer_state *YY_BUFFER_STATE;

extern int yyleng;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

/* The funky do-while in the following #define is used to turn the definition
 * int a single C statement (which needs a semi-colon terminator).  This
 * avoids problems with code like:
 *
 * 	if ( condition_holds )
 *		yyless( 5 );
 *	else
 *		do_something_else();
 *
 * Prior to using the do-while the compiler would get upset at the
 * "else" because it interpreted the "if" statement as being all
 * done when it reached the ';' after the yyless() call.
 */

/* Return all but the first 'n' matched characters back to the input stream. */

#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		*yy_cp = yy_hold_char; \
		YY_RESTORE_YY_MORE_OFFSET \
		yy_c_buf_p = yy_cp = yy_bp + n - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, yytext_ptr )

/* The following is because we cannot portably get our hands on size_t
 * (without autoconf's help, which isn't available because we want
 * flex-generated scanners to compile on their own).
 */
typedef unsigned int yy_size_t;


struct yy_buffer_state
	{
	istream* yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;
#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2
	};


/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 */
#define YY_CURRENT_BUFFER yy_current_buffer



static void *yy_flex_alloc YY_PROTO(( yy_size_t ));
static void *yy_flex_realloc YY_PROTO(( void *, yy_size_t ));
static void yy_flex_free YY_PROTO(( void * ));

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (yy_current_buffer->yy_at_bol)

typedef unsigned char YY_CHAR;
#define yytext_ptr yytext
#define YY_INTERACTIVE

#include <FlexLexer.h>


/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yytext_ptr = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yy_c_buf_p = yy_cp;

#define YY_NUM_RULES 74
#define YY_END_OF_BUFFER 75
static yyconst short int yy_accept[369] =
    {   0,
       69,   69,   75,   74,   69,   70,   69,   40,   74,   65,
       66,   67,   73,   73,   73,   73,   57,   62,   56,   68,
       68,   68,   68,   68,   68,   68,   68,   68,   68,   68,
       68,   68,   68,   68,   68,   68,   68,   68,   68,   68,
       68,   68,   68,   68,   63,   74,   64,   69,   69,   59,
       38,    0,   73,   73,   73,   73,   73,   73,   61,   58,
       60,   68,   68,   68,   68,   68,   68,   68,   68,   68,
       68,   68,   68,   68,   68,   68,   68,   68,   68,   68,
       68,   68,   68,   29,   68,   68,   68,   68,   68,   68,
       68,   68,   68,   68,   68,   68,   68,   68,   68,   68,

       68,   39,    0,    0,    0,   73,    0,   68,   68,   68,
       68,   68,   68,   28,   68,   68,   68,   68,   68,   68,
       68,   68,   68,   34,   45,   68,   68,   68,   68,   68,
       27,   37,   68,   41,   68,   68,   68,   68,   68,   68,
       68,   68,   68,   68,   32,   47,    0,    0,    0,    0,
        0,    0,   68,   68,   68,   12,   51,   50,   26,   68,
       10,   68,   68,   68,   68,   68,   68,   68,   68,   11,
       68,   68,   49,   68,   68,   25,   68,   68,   68,   22,
       68,   68,   30,    9,   68,   20,    0,    0,    0,   72,
       68,   68,   68,   68,   68,   68,   68,   68,   68,   31,

       68,   68,   68,   68,   19,   55,   68,   68,   68,   68,
       68,   68,   68,   44,    0,    0,    0,    0,    0,    2,
       68,   68,   68,   68,   68,   68,    1,   48,   36,   68,
       68,   68,   68,   68,   68,   68,   68,   68,   46,   71,
       71,   71,   68,   68,   68,   68,   68,   68,   42,   68,
       68,   33,   68,   68,   68,   68,   68,   68,   68,   43,
       71,   71,   71,   71,   68,   68,   68,   68,   68,   68,
       68,   68,   68,   68,   68,   52,   68,   68,   68,   68,
       68,   68,   68,   68,   68,   68,   68,   68,   68,   68,
       68,   68,   68,   68,   35,   68,   68,   68,   68,   68,

       68,   68,   68,   68,   68,   68,   68,   68,   68,   68,
       68,   68,   68,   68,   68,   68,   14,   68,   68,   68,
        6,   68,    4,   68,   13,   68,   68,   68,   68,    5,
       68,    3,   68,   68,   68,   68,   68,   68,   68,   68,
       68,   68,   68,   68,   68,   68,   68,    8,   21,   68,
       68,   68,   54,    7,   53,   68,   16,   18,   68,   15,
       17,   68,   68,   68,   68,   24,   23,    0
    } ;

static yyconst int yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    4,    5,    1,    1,    1,    1,    6,    1,    7,
        8,    1,    1,    9,   10,   11,    1,   12,   13,   14,
       15,   16,   17,   18,   18,   18,   18,   19,    1,   20,
       21,   22,    1,    1,   23,   24,   24,   25,   26,   24,
       27,   24,   24,   24,   28,   24,   29,   30,   24,   31,
       24,   24,   32,   33,   24,   24,   24,   24,   24,   24,
        1,    1,    1,    1,   34,    1,   35,   36,   37,   38,

       39,   40,   41,   42,   43,   24,   44,   45,   46,   47,
       48,   49,   24,   50,   51,   52,   53,   54,   55,   56,
       24,   24,   57,   58,   59,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst int yy_meta[60] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    2,
        3,    4,    4,    4,    4,    4,    4,    4,    3,    1,
        1,    1,    2,    2,    2,    2,    2,    2,    2,    2,
        2,    2,    2,    2,    2,    2,    2,    2,    2,    2,
        2,    2,    2,    2,    2,    2,    2,    2,    2,    2,
        2,    2,    2,    2,    2,    2,    1,    1,    1
    } ;

static yyconst short int yy_base[372] =
    {   0,
        0,    0,  593,  594,  590,  594,  587,  569,  583,  594,
      594,  594,   49,   57,   65,   73,  567,  566,  565,    0,
      546,  528,   57,   71,  535,   58,  539,  543,  532,   56,
       51,   48,   64,  539,  530,  542,  528,   48,   74,   73,
      536,   72,  523,  534,  594,  514,  594,  569,  566,  594,
      594,  111,   99,  119,  120,  129,  137,  145,  594,  594,
      594,    0,  529,  519,  524,  531,  533,  513,  508,  510,
      514,  514,  513,  511,  517,  510,  517,  505,  503,  503,
      508,  515,  510,    0,  507,  496,  491,  493,  505,  496,
       68,  495,  504,  492,  489,  493,  498,  490,  482,  495,

      497,  594,  153,  161,  169,  176,  120,  489,  492,  483,
      484,  500,  483,    0,  484,  473,  485,  480,  475,  478,
      485,  476,  156,    0,    0,  471,  472,  465,  472,  470,
        0,    0,  463,    0,  461,  469,  157,  471,  457,  454,
      460,  459,  466,  453,  453,    0,  190,  491,  199,  207,
      215,  221,  454,  463,  465,  464,    0,    0,    0,  458,
        0,  449,  456,  447,  450,  452,  454,  442,  455,  454,
      435,  439,    0,  445,  429,    0,  431,  443,  444,    0,
      437,  440,    0,    0,  426,    0,  229,  237,  245,  594,
      438,  424,  426,  425,  422,  429,  434,  431,  422,    0,

      416,  424,  417,  416,    0,    0,  419,  415,  412,  410,
      412,  422,  406,    0,  252,  446,  260,  268,  276,    0,
      259,  406,  405,  402,  402,  400,    0,    0,  260,  399,
      400,  399,  400,  397,  411,  393,  397,  404,    0,  288,
      295,  302,  390,  407,  397,  396,  294,  386,    0,  385,
      402,    0,  392,  391,  378,  394,  379,  281,  392,    0,
      594,  322,  329,  336,  386,  379,  373,  372,  377,  288,
      374,  380,  373,  367,  366,    0,  382,  379,  369,  289,
      373,  367,  364,  370,  369,  376,  360,  363,  373,  359,
      356,  362,  361,  353,    0,  367,  351,  354,  347,  351,

      354,  351,  350,  349,  352,  353,  339,  343,  346,  343,
      342,  351,  340,  343,  344,  339,    0,  327,  341,  340,
        0,  339,    0,  329,    0,  322,  336,  335,  336,    0,
      333,    0,  323,  327,  328,  327,  315,  316,  322,  323,
      322,  318,  309,  308,  285,  290,  289,    0,    0,  281,
      286,  258,    0,    0,    0,  257,    0,    0,  161,    0,
        0,  158,  157,  158,   77,    0,    0,  594,  352,  354,
      356
    } ;

static yyconst short int yy_def[372] =
    {   0,
      368,    1,  368,  368,  368,  368,  368,  368,  368,  368,
      368,  368,  368,  368,  368,  368,  368,  368,  368,  369,
      369,  369,  369,  369,  369,  369,  369,  369,  369,  369,
      369,  369,  369,  369,  369,  369,  369,  369,  369,  369,
      369,  369,  369,  369,  368,  368,  368,  368,  368,  368,
      368,  368,  370,  371,  371,  368,  368,  368,  368,  368,
      368,  369,  369,  369,  369,  369,  369,  369,  369,  369,
      369,  369,  369,  369,  369,  369,  369,  369,  369,  369,
      369,  369,  369,  369,  369,  369,  369,  369,  369,  369,
      369,  369,  369,  369,  369,  369,  369,  369,  369,  369,

      369,  368,  368,  368,  368,  368,  368,  369,  369,  369,
      369,  369,  369,  369,  369,  369,  369,  369,  369,  369,
      369,  369,  369,  369,  369,  369,  369,  369,  369,  369,
      369,  369,  369,  369,  369,  369,  369,  369,  369,  369,
      369,  369,  369,  369,  369,  369,  368,  368,  368,  368,
      368,  368,  369,  369,  369,  369,  369,  369,  369,  369,
      369,  369,  369,  369,  369,  369,  369,  369,  369,  369,
      369,  369,  369,  369,  369,  369,  369,  369,  369,  369,
      369,  369,  369,  369,  369,  369,  368,  368,  368,  368,
      369,  369,  369,  369,  369,  369,  369,  369,  369,  369,

      369,  369,  369,  369,  369,  369,  369,  369,  369,  369,
      369,  369,  369,  369,  368,  368,  368,  368,  368,  369,
      369,  369,  369,  369,  369,  369,  369,  369,  369,  369,
      369,  369,  369,  369,  369,  369,  369,  369,  369,  368,
      368,  368,  369,  369,  369,  369,  369,  369,  369,  369,
      369,  369,  369,  369,  369,  369,  369,  369,  369,  369,
      368,  368,  368,  368,  369,  369,  369,  369,  369,  369,
      369,  369,  369,  369,  369,  369,  369,  369,  369,  369,
      369,  369,  369,  369,  369,  369,  369,  369,  369,  369,
      369,  369,  369,  369,  369,  369,  369,  369,  369,  369,

      369,  369,  369,  369,  369,  369,  369,  369,  369,  369,
      369,  369,  369,  369,  369,  369,  369,  369,  369,  369,
      369,  369,  369,  369,  369,  369,  369,  369,  369,  369,
      369,  369,  369,  369,  369,  369,  369,  369,  369,  369,
      369,  369,  369,  369,  369,  369,  369,  369,  369,  369,
      369,  369,  369,  369,  369,  369,  369,  369,  369,  369,
      369,  369,  369,  369,  369,  369,  369,    0,  368,  368,
      368
    } ;

static yyconst short int yy_nxt[654] =
    {   0,
        4,    5,    6,    7,    8,    9,   10,   11,   12,    4,
        4,   13,   14,   15,   16,   16,   16,   16,    4,   17,
       18,   19,   20,   20,   21,   22,   23,   20,   24,   25,
       26,   20,   27,   20,   28,   20,   29,   30,   31,   32,
       33,   20,   34,   20,   35,   36,   37,   38,   39,   40,
       41,   42,   43,   20,   44,   20,   45,   46,   47,   52,
       53,   53,   53,   53,   53,   53,   53,   52,   54,   54,
       54,   54,   54,   54,   54,   52,   55,   55,   55,   55,
       56,   57,   58,   52,   58,   58,   58,   58,   58,   58,
       58,   65,   70,   67,   75,   79,   71,   77,   81,   80,

       88,   89,   90,   76,   66,   68,   78,   93,   91,   52,
       96,   82,   92,   97,   98,  367,   83,  107,  135,  136,
       94,   99,  103,  104,  105,  103,  103,  103,  103,   52,
       52,  152,  152,  152,  152,  152,  152,  107,  107,   52,
       58,   58,   58,   58,   58,   58,   58,   52,   58,   58,
       58,   58,   58,   58,  106,   52,  106,  106,  106,  106,
      106,  106,  106,  147,  148,  148,  148,  148,  148,  148,
      148,  147,  149,  149,  149,  149,  149,  149,  149,  147,
      150,  150,  150,  150,  150,  151,  148,  106,  106,  106,
      106,  106,  106,  106,  167,  177,  366,  365,  364,  363,

      168,  187,  188,  189,  187,  187,  187,  187,  178,  147,
      148,  148,  148,  148,  148,  148,  148,  147,  148,  148,
      148,  148,  148,  148,  148,  147,  148,  148,  148,  148,
      148,  148,  190,  190,  190,  190,  190,  190,  190,  215,
      216,  216,  216,  216,  216,  216,  216,  215,  217,  217,
      217,  217,  217,  217,  217,  215,  218,  218,  218,  218,
      218,  219,  216,  240,  241,  242,  240,  240,  240,  240,
      215,  216,  216,  216,  216,  216,  216,  216,  215,  216,
      216,  216,  216,  216,  216,  216,  215,  216,  216,  216,
      216,  216,  216,  243,  250,  362,  361,  244,  251,  261,

      261,  261,  261,  261,  261,  261,  262,  262,  262,  262,
      262,  262,  262,  263,  263,  263,  263,  263,  264,  261,
      269,  279,  287,  297,  360,  359,  270,  358,  357,  356,
      288,  298,  280,  261,  261,  261,  261,  261,  261,  261,
      261,  261,  261,  261,  261,  261,  261,  261,  261,  261,
      261,  261,  261,   62,  355,   62,  106,  106,   58,   58,
      354,  353,  352,  351,  350,  349,  348,  347,  346,  345,
      344,  343,  342,  341,  340,  339,  338,  337,  336,  335,
      334,  333,  332,  331,  330,  329,  328,  327,  326,  325,
      324,  323,  322,  321,  320,  319,  318,  317,  316,  315,

      314,  313,  312,  311,  310,  309,  308,  307,  306,  305,
      304,  303,  302,  301,  300,  299,  296,  295,  294,  293,
      292,  291,  290,  289,  286,  285,  284,  283,  282,  281,
      278,  277,  276,  275,  274,  273,  272,  271,  268,  267,
      266,  265,  260,  259,  258,  257,  256,  255,  254,  253,
      252,  249,  248,  247,  246,  245,  215,  239,  238,  237,
      236,  235,  234,  233,  232,  231,  230,  229,  228,  227,
      226,  225,  224,  223,  222,  221,  220,  214,  213,  212,
      211,  210,  209,  208,  207,  206,  205,  204,  203,  202,
      201,  200,  199,  198,  197,  196,  195,  194,  193,  192,

      191,  147,  186,  185,  184,  183,  182,  181,  180,  179,
      176,  175,  174,  173,  172,  171,  170,  169,  166,  165,
      164,  163,  162,  161,  160,  159,  158,  157,  156,  155,
      154,  153,  146,  145,  144,  143,  142,  141,  140,  139,
      138,  137,  134,  133,  132,  131,  130,  129,  128,  127,
      126,  125,  124,  123,  122,  121,  120,  119,  118,  117,
      116,  115,  114,  113,  112,  111,  110,  109,  108,   49,
       48,  102,  101,  100,   95,   87,   86,   85,   84,   74,
       73,   72,   69,   64,   63,   61,   60,   59,   51,   50,
       49,   48,  368,    3,  368,  368,  368,  368,  368,  368,

      368,  368,  368,  368,  368,  368,  368,  368,  368,  368,
      368,  368,  368,  368,  368,  368,  368,  368,  368,  368,
      368,  368,  368,  368,  368,  368,  368,  368,  368,  368,
      368,  368,  368,  368,  368,  368,  368,  368,  368,  368,
      368,  368,  368,  368,  368,  368,  368,  368,  368,  368,
      368,  368,  368
    } ;

static yyconst short int yy_chk[654] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,   13,
       13,   13,   13,   13,   13,   13,   13,   14,   14,   14,
       14,   14,   14,   14,   14,   15,   15,   15,   15,   15,
       15,   15,   15,   16,   16,   16,   16,   16,   16,   16,
       16,   23,   26,   24,   30,   32,   26,   31,   33,   32,

       38,   38,   38,   30,   23,   24,   31,   40,   39,   53,
       42,   33,   39,   42,   42,  365,   33,   53,   91,   91,
       40,   42,   52,   52,   52,   52,   52,   52,   52,   54,
       55,  107,  107,  107,  107,  107,  107,   54,   55,   56,
       56,   56,   56,   56,   56,   56,   56,   57,   57,   57,
       57,   57,   57,   57,   57,   58,   58,   58,   58,   58,
       58,   58,   58,  103,  103,  103,  103,  103,  103,  103,
      103,  104,  104,  104,  104,  104,  104,  104,  104,  105,
      105,  105,  105,  105,  105,  105,  105,  106,  106,  106,
      106,  106,  106,  106,  123,  137,  364,  363,  362,  359,

      123,  147,  147,  147,  147,  147,  147,  147,  137,  149,
      149,  149,  149,  149,  149,  149,  149,  150,  150,  150,
      150,  150,  150,  150,  150,  151,  151,  151,  151,  151,
      151,  151,  152,  152,  152,  152,  152,  152,  152,  187,
      187,  187,  187,  187,  187,  187,  187,  188,  188,  188,
      188,  188,  188,  188,  188,  189,  189,  189,  189,  189,
      189,  189,  189,  215,  215,  215,  215,  215,  215,  215,
      217,  217,  217,  217,  217,  217,  217,  217,  218,  218,
      218,  218,  218,  218,  218,  218,  219,  219,  219,  219,
      219,  219,  219,  221,  229,  356,  352,  221,  229,  240,

      240,  240,  240,  240,  240,  240,  241,  241,  241,  241,
      241,  241,  241,  242,  242,  242,  242,  242,  242,  242,
      247,  258,  270,  280,  351,  350,  247,  347,  346,  345,
      270,  280,  258,  262,  262,  262,  262,  262,  262,  262,
      263,  263,  263,  263,  263,  263,  263,  264,  264,  264,
      264,  264,  264,  369,  344,  369,  370,  370,  371,  371,
      343,  342,  341,  340,  339,  338,  337,  336,  335,  334,
      333,  331,  329,  328,  327,  326,  324,  322,  320,  319,
      318,  316,  315,  314,  313,  312,  311,  310,  309,  308,
      307,  306,  305,  304,  303,  302,  301,  300,  299,  298,

      297,  296,  294,  293,  292,  291,  290,  289,  288,  287,
      286,  285,  284,  283,  282,  281,  279,  278,  277,  275,
      274,  273,  272,  271,  269,  268,  267,  266,  265,  259,
      257,  256,  255,  254,  253,  251,  250,  248,  246,  245,
      244,  243,  238,  237,  236,  235,  234,  233,  232,  231,
      230,  226,  225,  224,  223,  222,  216,  213,  212,  211,
      210,  209,  208,  207,  204,  203,  202,  201,  199,  198,
      197,  196,  195,  194,  193,  192,  191,  185,  182,  181,
      179,  178,  177,  175,  174,  172,  171,  170,  169,  168,
      167,  166,  165,  164,  163,  162,  160,  156,  155,  154,

      153,  148,  145,  144,  143,  142,  141,  140,  139,  138,
      136,  135,  133,  130,  129,  128,  127,  126,  122,  121,
      120,  119,  118,  117,  116,  115,  113,  112,  111,  110,
      109,  108,  101,  100,   99,   98,   97,   96,   95,   94,
       93,   92,   90,   89,   88,   87,   86,   85,   83,   82,
       81,   80,   79,   78,   77,   76,   75,   74,   73,   72,
       71,   70,   69,   68,   67,   66,   65,   64,   63,   49,
       48,   46,   44,   43,   41,   37,   36,   35,   34,   29,
       28,   27,   25,   22,   21,   19,   18,   17,    9,    8,
        7,    5,    3,  368,  368,  368,  368,  368,  368,  368,

      368,  368,  368,  368,  368,  368,  368,  368,  368,  368,
      368,  368,  368,  368,  368,  368,  368,  368,  368,  368,
      368,  368,  368,  368,  368,  368,  368,  368,  368,  368,
      368,  368,  368,  368,  368,  368,  368,  368,  368,  368,
      368,  368,  368,  368,  368,  368,  368,  368,  368,  368,
      368,  368,  368
    } ;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
#line 1 "pentestscanner.l"
#define INITIAL 0
#line 2 "pentestscanner.l"

#include "ptsYacc.tab.hpp"
#include "pts.yy.h"
#include "global.h"

int lineNo=1;
ifstream mFile;
FlexLexer* fileFlex;

#line 599 "ptsLex.yy.cpp"

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap YY_PROTO(( void ));
#else
extern int yywrap YY_PROTO(( void ));
#endif
#endif


#ifndef yytext_ptr
static void yy_flex_strncpy YY_PROTO(( char *, yyconst char *, int ));
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen YY_PROTO(( yyconst char * ));
#endif

#ifndef YY_NO_INPUT
#endif

#if YY_STACK_USED
static int yy_start_stack_ptr = 0;
static int yy_start_stack_depth = 0;
static int *yy_start_stack = 0;
#ifndef YY_NO_PUSH_STATE
static void yy_push_state YY_PROTO(( int new_state ));
#endif
#ifndef YY_NO_POP_STATE
static void yy_pop_state YY_PROTO(( void ));
#endif
#ifndef YY_NO_TOP_STATE
static int yy_top_state YY_PROTO(( void ));
#endif

#else
#define YY_NO_PUSH_STATE 1
#define YY_NO_POP_STATE 1
#define YY_NO_TOP_STATE 1
#endif

#ifdef YY_MALLOC_DECL
YY_MALLOC_DECL
#else
#if __STDC__
#ifndef __cplusplus
#include <stdlib.h>
#endif
#else
/* Just try to get by without declaring the routines.  This will fail
 * miserably on non-ANSI systems for which sizeof(size_t) != sizeof(int)
 * or sizeof(void*) != sizeof(int).
 */
#endif
#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */

#ifndef ECHO
#define ECHO LexerOutput( yytext, yyleng )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( (result = LexerInput( (char *) buf, max_size )) < 0 ) \
		YY_FATAL_ERROR( "input in flex scanner failed" );
#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) LexerError( msg )
#endif

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL int yyFlexLexer::yylex()
#endif

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

YY_DECL
	{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;

#line 15 "pentestscanner.l"


#line 729 "ptsLex.yy.cpp"

	if ( yy_init )
		{
		yy_init = 0;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yy_start )
			yy_start = 1;	/* first start state */

		if ( ! yyin )
			yyin = &cin;

		if ( ! yyout )
			yyout = &cout;

		if ( ! yy_current_buffer )
			yy_current_buffer =
				yy_create_buffer( yyin, YY_BUF_SIZE );

		yy_load_buffer_state();
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yy_start;
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				yy_last_accepting_state = yy_current_state;
				yy_last_accepting_cpos = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 369 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 594 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;


do_action:	/* This label is used only to access EOF actions. */


		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = yy_hold_char;
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			goto yy_find_action;

case 1:
#line 18 "pentestscanner.l"
case 2:
YY_RULE_SETUP
#line 18 "pentestscanner.l"
return	DEFINE;
	YY_BREAK
case 3:
#line 21 "pentestscanner.l"
case 4:
YY_RULE_SETUP
#line 21 "pentestscanner.l"
return	PENTESTTIME;
	YY_BREAK
case 5:
#line 24 "pentestscanner.l"
case 6:
YY_RULE_SETUP
#line 24 "pentestscanner.l"
return	PENTESTGOAL;
	YY_BREAK
case 7:
#line 27 "pentestscanner.l"
case 8:
YY_RULE_SETUP
#line 27 "pentestscanner.l"
return	PENTESTTARGET;
	YY_BREAK
case 9:
#line 30 "pentestscanner.l"
case 10:
YY_RULE_SETUP
#line 30 "pentestscanner.l"
return	TIME;			
	YY_BREAK
case 11:
#line 33 "pentestscanner.l"
case 12:
YY_RULE_SETUP
#line 33 "pentestscanner.l"
return	GOAL;
	YY_BREAK
case 13:
#line 36 "pentestscanner.l"
case 14:
YY_RULE_SETUP
#line 36 "pentestscanner.l"
return	EXPECTATION;
	YY_BREAK
case 15:
#line 39 "pentestscanner.l"
case 16:
YY_RULE_SETUP
#line 39 "pentestscanner.l"
return	GAINPRIVILEGE;
	YY_BREAK
case 17:
#line 42 "pentestscanner.l"
case 18:
YY_RULE_SETUP
#line 42 "pentestscanner.l"
return	GOALPRIVILEGE;
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 44 "pentestscanner.l"
return	GUEST;
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 45 "pentestscanner.l"
return	USER;
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 46 "pentestscanner.l"
return	ADMINISTRATOR;
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 47 "pentestscanner.l"
return	ROOT;
	YY_BREAK
case 23:
#line 50 "pentestscanner.l"
case 24:
YY_RULE_SETUP
#line 50 "pentestscanner.l"
return	EXPECTEPRIVILEGE;
	YY_BREAK
case 25:
#line 53 "pentestscanner.l"
case 26:
YY_RULE_SETUP
#line 53 "pentestscanner.l"
return	PATH;
	YY_BREAK
case 27:
#line 56 "pentestscanner.l"
case 28:
YY_RULE_SETUP
#line 56 "pentestscanner.l"
return	NOW;
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 58 "pentestscanner.l"
return	IF;
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 59 "pentestscanner.l"
return	THEN;
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 60 "pentestscanner.l"
return	ENDIF;
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 62 "pentestscanner.l"
return USE;
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 63 "pentestscanner.l"
return EXPLOIT;
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 64 "pentestscanner.l"
return FOR;
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 65 "pentestscanner.l"
return PENETRATE;
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 66 "pentestscanner.l"
return EXPECT;
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 67 "pentestscanner.l"
return OUT;
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 70 "pentestscanner.l"
return AND;
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 71 "pentestscanner.l"
return OR;
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 72 "pentestscanner.l"
return NOT;
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 74 "pentestscanner.l"
return OWN;
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 75 "pentestscanner.l"
return CONNECT;
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 76 "pentestscanner.l"
return SERVICE;
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 77 "pentestscanner.l"
return TRUST;
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 79 "pentestscanner.l"
return FTP;
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 80 "pentestscanner.l"
return TELNET;
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 81 "pentestscanner.l"
return WEB;
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 83 "pentestscanner.l"
return DOMAIN;
	YY_BREAK
case 49:
#line 86 "pentestscanner.l"
case 50:
#line 87 "pentestscanner.l"
case 51:
YY_RULE_SETUP
#line 87 "pentestscanner.l"
return MASK;
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 89 "pentestscanner.l"
return OVERFLOW;			
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 90 "pentestscanner.l"
return RACECONDITON;
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 91 "pentestscanner.l"
return PASSWORDCRACK;
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 92 "pentestscanner.l"
return LOGIN;
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 95 "pentestscanner.l"
return LARGER;
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 96 "pentestscanner.l"
return LESS;		
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 97 "pentestscanner.l"
return EQUAL;
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 98 "pentestscanner.l"
return NOTEQUAL;
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 99 "pentestscanner.l"
return LARGEREQUAL;
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 100 "pentestscanner.l"
return LESSEQUAL;
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 101 "pentestscanner.l"
return ASSIGN;
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 103 "pentestscanner.l"
return LEFT_BIG_BRACKET;
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 104 "pentestscanner.l"
return RIGHT_BIG_BRACKET;
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 105 "pentestscanner.l"
return LEFT_SMALL_BRACKET;
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 106 "pentestscanner.l"
return RIGHT_SMALL_BRACKET;
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 107 "pentestscanner.l"
return COMM;
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 109 "pentestscanner.l"
{yylval.sval=strdup(yytext);return STRING;}
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 111 "pentestscanner.l"
;
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 112 "pentestscanner.l"
lineNo += 1;
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 113 "pentestscanner.l"
{yylval.sval=strdup(yytext);return IPADDR;/*IPµØÖ·0.0.0.1-255.255.255.255*/} 
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 114 "pentestscanner.l"
{yylval.sval=strdup(yytext);return TIMECONSTANT;/*Ê±¼ä·¶Î§00:00-23:59*/} 
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 115 "pentestscanner.l"
{yylval.ival=atoi(yytext);return NUMBER;}
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 118 "pentestscanner.l"
ECHO;
	YY_BREAK
#line 1140 "ptsLex.yy.cpp"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - yytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yy_hold_char;
		YY_RESTORE_YY_MORE_OFFSET

		if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between yy_current_buffer and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yy_n_chars = yy_current_buffer->yy_n_chars;
			yy_current_buffer->yy_input_file = yyin;
			yy_current_buffer->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yy_c_buf_p <= &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yy_c_buf_p = yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state();

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = yy_c_buf_p;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer() )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yy_did_buffer_switch_on_eof = 0;

				if ( yywrap() )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yy_c_buf_p =
					yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yy_c_buf_p =
				&yy_current_buffer->yy_ch_buf[yy_n_chars];

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of yylex */

yyFlexLexer::yyFlexLexer( istream* arg_yyin, ostream* arg_yyout )
	{
	yyin = arg_yyin;
	yyout = arg_yyout;
	yy_c_buf_p = 0;
	yy_init = 1;
	yy_start = 0;
	yy_flex_debug = 0;
	yylineno = 1;	// this will only get updated if %option yylineno

	yy_did_buffer_switch_on_eof = 0;

	yy_looking_for_trail_begin = 0;
	yy_more_flag = 0;
	yy_more_len = 0;
	yy_more_offset = yy_prev_more_offset = 0;

	yy_start_stack_ptr = yy_start_stack_depth = 0;
	yy_start_stack = 0;

	yy_current_buffer = 0;

#ifdef YY_USES_REJECT
	yy_state_buf = new yy_state_type[YY_BUF_SIZE + 2];
#else
	yy_state_buf = 0;
#endif
	}

yyFlexLexer::~yyFlexLexer()
	{
	delete yy_state_buf;
	yy_delete_buffer( yy_current_buffer );
	}

void yyFlexLexer::switch_streams( istream* new_in, ostream* new_out )
	{
	if ( new_in )
		{
		yy_delete_buffer( yy_current_buffer );
		yy_switch_to_buffer( yy_create_buffer( new_in, YY_BUF_SIZE ) );
		}

	if ( new_out )
		yyout = new_out;
	}

#ifdef YY_INTERACTIVE
int yyFlexLexer::LexerInput( char* buf, int /* max_size */ )
#else
int yyFlexLexer::LexerInput( char* buf, int max_size )
#endif
	{
	if ( yyin->eof() || yyin->fail() )
		return 0;

#ifdef YY_INTERACTIVE
	yyin->get( buf[0] );

	if ( yyin->eof() )
		return 0;

	if ( yyin->bad() )
		return -1;

	return 1;

#else
	(void) yyin->read( buf, max_size );

	if ( yyin->bad() )
		return -1;
	else
		return yyin->gcount();
#endif
	}

void yyFlexLexer::LexerOutput( const char* buf, int size )
	{
	(void) yyout->write( buf, size );
	}

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */

int yyFlexLexer::yy_get_next_buffer()
	{
	register char *dest = yy_current_buffer->yy_ch_buf;
	register char *source = yytext_ptr;
	register int number_to_move, i;
	int ret_val;

	if ( yy_c_buf_p > &yy_current_buffer->yy_ch_buf[yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( yy_current_buffer->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yy_c_buf_p - yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (yy_c_buf_p - yytext_ptr) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		yy_current_buffer->yy_n_chars = yy_n_chars = 0;

	else
		{
		int num_to_read =
			yy_current_buffer->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */
#ifdef YY_USES_REJECT
			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );
#else

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = yy_current_buffer;

			int yy_c_buf_p_offset =
				(int) (yy_c_buf_p - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yy_flex_realloc( (void *) b->yy_ch_buf,
							 b->yy_buf_size + 2 );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = yy_current_buffer->yy_buf_size -
						number_to_move - 1;
#endif
			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&yy_current_buffer->yy_ch_buf[number_to_move]),
			yy_n_chars, num_to_read );

		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	if ( yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			yy_current_buffer->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	yy_n_chars += number_to_move;
	yy_current_buffer->yy_ch_buf[yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	yy_current_buffer->yy_ch_buf[yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yytext_ptr = &yy_current_buffer->yy_ch_buf[0];

	return ret_val;
	}


/* yy_get_previous_state - get the state just before the EOB char was reached */

yy_state_type yyFlexLexer::yy_get_previous_state()
	{
	register yy_state_type yy_current_state;
	register char *yy_cp;

	yy_current_state = yy_start;

	for ( yy_cp = yytext_ptr + YY_MORE_ADJ; yy_cp < yy_c_buf_p; ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			yy_last_accepting_state = yy_current_state;
			yy_last_accepting_cpos = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 369 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
	}


/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */

yy_state_type yyFlexLexer::yy_try_NUL_trans( yy_state_type yy_current_state )
	{
	register int yy_is_jam;
	register char *yy_cp = yy_c_buf_p;

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		yy_last_accepting_state = yy_current_state;
		yy_last_accepting_cpos = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 369 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 368);

	return yy_is_jam ? 0 : yy_current_state;
	}


void yyFlexLexer::yyunput( int c, register char* yy_bp )
	{
	register char *yy_cp = yy_c_buf_p;

	/* undo effects of setting up yytext */
	*yy_cp = yy_hold_char;

	if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = yy_n_chars + 2;
		register char *dest = &yy_current_buffer->yy_ch_buf[
					yy_current_buffer->yy_buf_size + 2];
		register char *source =
				&yy_current_buffer->yy_ch_buf[number_to_move];

		while ( source > yy_current_buffer->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		yy_current_buffer->yy_n_chars =
			yy_n_chars = yy_current_buffer->yy_buf_size;

		if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;


	yytext_ptr = yy_bp;
	yy_hold_char = *yy_cp;
	yy_c_buf_p = yy_cp;
	}


int yyFlexLexer::yyinput()
	{
	int c;

	*yy_c_buf_p = yy_hold_char;

	if ( *yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yy_c_buf_p < &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			/* This was really a NUL. */
			*yy_c_buf_p = '\0';

		else
			{ /* need more input */
			int offset = yy_c_buf_p - yytext_ptr;
			++yy_c_buf_p;

			switch ( yy_get_next_buffer() )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/* fall through */

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap() )
						return EOF;

					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yy_c_buf_p = yytext_ptr + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) yy_c_buf_p;	/* cast for 8-bit char's */
	*yy_c_buf_p = '\0';	/* preserve yytext */
	yy_hold_char = *++yy_c_buf_p;


	return c;
	}


void yyFlexLexer::yyrestart( istream* input_file )
	{
	if ( ! yy_current_buffer )
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE );

	yy_init_buffer( yy_current_buffer, input_file );
	yy_load_buffer_state();
	}


void yyFlexLexer::yy_switch_to_buffer( YY_BUFFER_STATE new_buffer )
	{
	if ( yy_current_buffer == new_buffer )
		return;

	if ( yy_current_buffer )
		{
		/* Flush out information for old buffer. */
		*yy_c_buf_p = yy_hold_char;
		yy_current_buffer->yy_buf_pos = yy_c_buf_p;
		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	yy_current_buffer = new_buffer;
	yy_load_buffer_state();

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yy_did_buffer_switch_on_eof = 1;
	}


void yyFlexLexer::yy_load_buffer_state()
	{
	yy_n_chars = yy_current_buffer->yy_n_chars;
	yytext_ptr = yy_c_buf_p = yy_current_buffer->yy_buf_pos;
	yyin = yy_current_buffer->yy_input_file;
	yy_hold_char = *yy_c_buf_p;
	}


YY_BUFFER_STATE yyFlexLexer::yy_create_buffer( istream* file, int size )
	{
	YY_BUFFER_STATE b;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yy_flex_alloc( b->yy_buf_size + 2 );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
	}


void yyFlexLexer::yy_delete_buffer( YY_BUFFER_STATE b )
	{
	if ( ! b )
		return;

	if ( b == yy_current_buffer )
		yy_current_buffer = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yy_flex_free( (void *) b->yy_ch_buf );

	yy_flex_free( (void *) b );
	}


extern "C" int isatty YY_PROTO(( int ));
void yyFlexLexer::yy_init_buffer( YY_BUFFER_STATE b, istream* file )

	{
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

	b->yy_is_interactive = 0;
	}


void yyFlexLexer::yy_flush_buffer( YY_BUFFER_STATE b )
	{
	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == yy_current_buffer )
		yy_load_buffer_state();
	}


#ifndef YY_NO_SCAN_BUFFER
#endif


#ifndef YY_NO_SCAN_STRING
#endif


#ifndef YY_NO_SCAN_BYTES
#endif


#ifndef YY_NO_PUSH_STATE
void yyFlexLexer::yy_push_state( int new_state )
	{
	if ( yy_start_stack_ptr >= yy_start_stack_depth )
		{
		yy_size_t new_size;

		yy_start_stack_depth += YY_START_STACK_INCR;
		new_size = yy_start_stack_depth * sizeof( int );

		if ( ! yy_start_stack )
			yy_start_stack = (int *) yy_flex_alloc( new_size );

		else
			yy_start_stack = (int *) yy_flex_realloc(
					(void *) yy_start_stack, new_size );

		if ( ! yy_start_stack )
			YY_FATAL_ERROR(
			"out of memory expanding start-condition stack" );
		}

	yy_start_stack[yy_start_stack_ptr++] = YY_START;

	BEGIN(new_state);
	}
#endif


#ifndef YY_NO_POP_STATE
void yyFlexLexer::yy_pop_state()
	{
	if ( --yy_start_stack_ptr < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN(yy_start_stack[yy_start_stack_ptr]);
	}
#endif


#ifndef YY_NO_TOP_STATE
int yyFlexLexer::yy_top_state()
	{
	return yy_start_stack[yy_start_stack_ptr - 1];
	}
#endif

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif


void yyFlexLexer::LexerError( yyconst char msg[] )
	{
	cerr << msg << '\n';
	exit( YY_EXIT_FAILURE );
	}


/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		yytext[yyleng] = yy_hold_char; \
		yy_c_buf_p = yytext + n; \
		yy_hold_char = *yy_c_buf_p; \
		*yy_c_buf_p = '\0'; \
		yyleng = n; \
		} \
	while ( 0 )


/* Internal utility routines. */

#ifndef yytext_ptr
#ifdef YY_USE_PROTOS
static void yy_flex_strncpy( char *s1, yyconst char *s2, int n )
#else
static void yy_flex_strncpy( s1, s2, n )
char *s1;
yyconst char *s2;
int n;
#endif
	{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
	}
#endif

#ifdef YY_NEED_STRLEN
#ifdef YY_USE_PROTOS
static int yy_flex_strlen( yyconst char *s )
#else
static int yy_flex_strlen( s )
yyconst char *s;
#endif
	{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
	}
#endif


#ifdef YY_USE_PROTOS
static void *yy_flex_alloc( yy_size_t size )
#else
static void *yy_flex_alloc( size )
yy_size_t size;
#endif
	{
	return (void *) malloc( size );
	}

#ifdef YY_USE_PROTOS
static void *yy_flex_realloc( void *ptr, yy_size_t size )
#else
static void *yy_flex_realloc( ptr, size )
void *ptr;
yy_size_t size;
#endif
	{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
	}

#ifdef YY_USE_PROTOS
static void yy_flex_free( void *ptr )
#else
static void yy_flex_free( ptr )
void *ptr;
#endif
	{
	free( ptr );
	}

#if YY_MAIN
int main()
	{
	yylex();
	return 0;
	}
#endif
#line 118 "pentestscanner.l"


int yylex()
{
	return fileFlex->yylex();
}

int yyInitLexer(char *file)
{
	mFile.clear();
	mFile.open(file);
	if (!mFile)
	{
		//cout<<"Cann't open the file!"<<endl;
		return 1;
	}

	fileFlex = new yyFlexLexer(&mFile,NULL);
	return 0;
}

int yyCloseFile()
{
	mFile.close();
	return 0;
}

int yywrap()
{
	return 1;
}
